name: ci

# Controls when the action will run
on:

  # Trigger the workflow on all pushes, except on tag creation
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'

  # Trigger the workflow on all pull requests
  pull_request: ~

  # Allow workflow to be dispatched on demand
  workflow_dispatch: ~

jobs:
  ci:
    name: ci
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        - ubuntu-18.04
        - macos-10.15
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build & Test
      uses: ecmwf-actions/build-package@v1
